/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\eyepop_squats_ui_2.glb -T -p 6 -j -s -K -k -R 2048 
Files: .\eyepop_squats_ui_2.glb [4.05MB] > C:\Users\edmun\OneDrive\Documents\_SPACE\EyePop\EyePopDemos\node\basic-eyepop-example\src\assets\eyepop_squats_ui_2-transformed.glb [507.45KB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/eyepop_squats_ui_2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="tick_1" castShadow receiveShadow geometry={nodes.tick_1.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_2" castShadow receiveShadow geometry={nodes.tick_2.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_3" castShadow receiveShadow geometry={nodes.tick_3.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_4" castShadow receiveShadow geometry={nodes.tick_4.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_5" castShadow receiveShadow geometry={nodes.tick_5.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_6" castShadow receiveShadow geometry={nodes.tick_6.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_7" castShadow receiveShadow geometry={nodes.tick_7.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_8" castShadow receiveShadow geometry={nodes.tick_8.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_9" castShadow receiveShadow geometry={nodes.tick_9.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_10" castShadow receiveShadow geometry={nodes.tick_10.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_11" castShadow receiveShadow geometry={nodes.tick_11.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_12" castShadow receiveShadow geometry={nodes.tick_12.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_13" castShadow receiveShadow geometry={nodes.tick_13.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_14" castShadow receiveShadow geometry={nodes.tick_14.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_15" castShadow receiveShadow geometry={nodes.tick_15.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_16" castShadow receiveShadow geometry={nodes.tick_16.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_17" castShadow receiveShadow geometry={nodes.tick_17.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_18" castShadow receiveShadow geometry={nodes.tick_18.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_19" castShadow receiveShadow geometry={nodes.tick_19.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_20" castShadow receiveShadow geometry={nodes.tick_20.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="tick_21" castShadow receiveShadow geometry={nodes.tick_21.geometry} material={materials.eyepop_blue} position={[0, 0, 2.54]} />
        <mesh name="bg" castShadow receiveShadow geometry={nodes.bg.geometry} material={materials['bake.002']} position={[0, 0, 0.037076]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="indicator" castShadow receiveShadow geometry={nodes.indicator.geometry} material={materials['bake.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/eyepop_squats_ui_2-transformed.glb')
