const pop_uuid = '';
const pop_endpoint = "https://api.eyepop.ai/pops/" + pop_uuid + "/config?auto_start=true";

// Do not expose your API key in production! You can leave this blank in development.
const api_key = '';

// You can create a temporary token for your users to authenticate with. Keeping this blank in development will allow you to login to authenticate.
// https://docs.eyepop.ai/developer-documentation/api-key
const token = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InFUTWx1V2dRLXgxS1JhUlFMWDZueSJ9.eyJlbWFpbCI6ImVkbXVuZGRhb0BnbWFpbC5jb20iLCJodHRwczovL2NsYWltcy5leWVwb3AuYWkvZ3JhbnRzIjpbeyJwZXJtaXNzaW9uIjoiYWNjZXNzOmluZmVyZW5jZS1hcGkiLCJ0YXJnZXQiOiJ1c2VyOmF1dGgwfDY1N2NhZTZlZWNlNjk1OTA3OGQ5Njg5ZiJ9XSwiaXNzIjoiaHR0cHM6Ly9leWVwb3AudXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY1N2NhZTZlZWNlNjk1OTA3OGQ5Njg5ZiIsImF1ZCI6WyJodHRwczovL2FwaS5leWVwb3AuYWkiLCJodHRwczovL2V5ZXBvcC51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzA2ODI0MTE4LCJleHAiOjE3MDY5MTA1MTgsImF6cCI6IlV3VU02WDNndTBMZ2gzdEFDcFEwS3U0bXlsWWRLYjk1Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbXX0.LRwPUoVOVqDMQrGB6jGt9O0fjApzzOiwC7xysk9I_SKpU1W0gA_q6hzhkLXgdTaUgp4bbM2Pdj8MIvnHOZQ9WHlKgQ8xMFiU7v_IqAIydNbRAU899qFgoJINfKJ5RLCA8_8n8EU7p5gaoUuWt5K26EE2I0z3l9TCcWP_kqxlNglttHfutb8DhkHDE5Cgfs4RPCFJiDXwJmGjPA9xlUOosdIBdxv5nYSTaHEqYTCAkZkWeHJXLg33xPep48IGT6V32KSXs3lIxQ0uvqcE9xEhNkT3sH6aFAw9qSuLzlrpvhQtCwTrhLQZ-BnzGJyRZzMQ0x-D6iftKhJl_d2eC6G8gQ';


var config = {};
